nelmio_cors:
    defaults:
        origin_regex: true
        allow_origin: ['%env(CORS_ALLOW_ORIGIN)%']
        allow_methods: ['GET', 'OPTIONS', 'POST', 'PUT', 'PATCH', 'DELETE']
        allow_headers: ['X-Custom-Auth', 'Content-Type', 'Authorization','Origin', 'Accept', 'Bearer']
        expose_headers: ['Link']
        max_age: 3600
    paths:
        '^/api':
            origin_regex: true
            allow_origin: ['%env(CORS_ALLOW_ORIGIN)%']
            allow_methods: ['POST', 'OPTIONS','PUT', 'GET','PATCH', 'DELETE']
            allow_headers: ['X-Custom-Auth', 'Content-Type', 'Authorization','Origin', 'Accept', 'Bearer']
        '^/':
            origin_regex: true
            allow_origin: ['%env(CORS_ALLOW_ORIGIN)%']
            allow_headers: ['X-Custom-Auth','Content-Type','Authorization','Origin', 'Accept', 'Bearer']
            allow_methods: ['POST', 'PUT', 'GET','PATCH', 'DELETE']
            max_age: 3600
